const PDFDocument = require('pdfkit');
const fs = require('fs');
const path = require('path');

/**
 * Generate a handwriting collection template PDF
 *
 * The template includes boxes for all characters:
 * - 26 uppercase letters (A-Z)
 * - 26 lowercase letters (a-z)
 * - 10 numbers (0-9)
 * - 11 symbols (.,!?;:'"()-)
 * Total: 73 characters
 */

const ALL_CHARACTERS = {
  'Uppercase Letters (A-Z)': 'ABCDEFGHIJKLMNOPQRSTUVWXYZ'.split(''),
  'Lowercase Letters (a-z)': 'abcdefghijklmnopqrstuvwxyz'.split(''),
  'Numbers (0-9)': '0123456789'.split(''),
  'Symbols': '.,!?;:\'"()-'.split('')
};

/**
 * Generate handwriting template PDF
 *
 * @param {Stream} outputStream - Output stream to write PDF to
 * @returns {Promise<void>}
 */
function generateTemplate(outputStream) {
  return new Promise((resolve, reject) => {
    const doc = new PDFDocument({
      size: 'LETTER',
      margins: {
        top: 50,
        bottom: 50,
        left: 50,
        right: 50
      }
    });

    // Pipe to output stream
    doc.pipe(outputStream);

    // Handle completion
    outputStream.on('finish', resolve);
    outputStream.on('error', reject);

    // Configuration
    const boxSize = 80;
    const boxPadding = 10;
    const boxesPerRow = 6;
    const labelHeight = 30;
    const sectionSpacing = 40;

    let currentY = doc.page.margins.top;

    // Title
    doc.fontSize(24)
       .font('Helvetica-Bold')
       .text('Handwriting Collection Template', 50, currentY, { align: 'center' });

    currentY += 40;

    // Instructions
    doc.fontSize(10)
       .font('Helvetica')
       .text('Instructions:', 50, currentY);
    currentY += 15;

    doc.fontSize(9)
       .text('1. Print this template on white paper', 70, currentY);
    currentY += 12;
    doc.text('2. Write each character naturally in its box using a black pen', 70, currentY);
    currentY += 12;
    doc.text('3. Keep your handwriting centered and consistent in size', 70, currentY);
    currentY += 12;
    doc.text('4. Scan or photograph the completed sheet (ensure good lighting and contrast)', 70, currentY);
    currentY += 12;
    doc.text('5. Upload the image to the app to generate your custom font', 70, currentY);

    currentY += sectionSpacing;

    // Draw character boxes by section
    Object.entries(ALL_CHARACTERS).forEach(([sectionName, chars], sectionIndex) => {
      // Check if we need a new page
      const rowsNeeded = Math.ceil(chars.length / boxesPerRow);
      const sectionHeight = labelHeight + (rowsNeeded * (boxSize + boxPadding));

      if (currentY + sectionHeight > doc.page.height - doc.page.margins.bottom) {
        doc.addPage();
        currentY = doc.page.margins.top;
      }

      // Section label
      doc.fontSize(12)
         .font('Helvetica-Bold')
         .text(sectionName, 50, currentY);
      currentY += labelHeight;

      // Draw boxes for this section
      let charIndex = 0;
      while (charIndex < chars.length) {
        const charsInRow = Math.min(boxesPerRow, chars.length - charIndex);

        // Check if we need a new page for this row
        if (currentY + boxSize > doc.page.height - doc.page.margins.bottom) {
          doc.addPage();
          currentY = doc.page.margins.top;
        }

        for (let i = 0; i < charsInRow; i++) {
          const char = chars[charIndex + i];
          const x = 50 + (i * (boxSize + boxPadding));

          // Draw box
          doc.rect(x, currentY, boxSize, boxSize)
             .stroke();

          // Draw character label below box
          doc.fontSize(8)
             .font('Helvetica')
             .text(char === ' ' ? 'space' : char, x, currentY + boxSize + 3, {
               width: boxSize,
               align: 'center'
             });

          // Draw light guidelines in box
          doc.save();
          doc.strokeOpacity(0.2);

          // Horizontal centerline
          doc.moveTo(x, currentY + boxSize / 2)
             .lineTo(x + boxSize, currentY + boxSize / 2)
             .stroke();

          // Vertical centerline
          doc.moveTo(x + boxSize / 2, currentY)
             .lineTo(x + boxSize / 2, currentY + boxSize)
             .stroke();

          doc.restore();
        }

        charIndex += charsInRow;
        currentY += boxSize + boxPadding + 12; // Extra space for labels
      }

      currentY += sectionSpacing - boxPadding;
    });

    // Footer on last page
    const footerY = doc.page.height - doc.page.margins.bottom + 20;
    doc.fontSize(8)
       .font('Helvetica')
       .text('Generated by Handwriting App', 50, footerY, {
         align: 'center',
         width: doc.page.width - 100
       });

    // Finalize PDF
    doc.end();
  });
}

/**
 * Generate template and save to file
 *
 * @param {string} outputPath - Path to save PDF
 * @returns {Promise<void>}
 */
function generateTemplateFile(outputPath) {
  const outputStream = fs.createWriteStream(outputPath);
  return generateTemplate(outputStream);
}

module.exports = {
  generateTemplate,
  generateTemplateFile,
  ALL_CHARACTERS
};
